import paramiko, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
n = paramiko.SSHClient()
n.set_missing_host_key_policy(paramiko.AutoAddPolicy())
n.connect('100.70.136.90', username='root', password='alex', timeout=30)
s,o,e = n.exec_command("pct exec 100 -- pm2 show vannes-batteries 2>&1 | grep -E 'status|uptime|script path|exec cwd'", timeout=30)
print(o.read().decode())
s2,o2,e2 = n.exec_command("pct exec 100 -- curl -so /dev/null -w '%{http_code}' http://localhost:3000 2>&1", timeout=15)
print(f"Local Next.js: {o2.read().decode()}")
n.close()
